// This file is automatically generated. Do not edit it directly.
// MODIFIED: Added storageKey isolation for dual session support (tenant vs owner)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("❌ Variables Supabase manquantes ! Vérifiez VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY");
}

// Détermine le contexte de l'application (tenant ou owner) pour isoler les sessions
// Permet d'avoir deux sessions actives simultanément sur des ports différents
const APP_CONTEXT = import.meta.env.VITE_APP_CONTEXT || 'tenant'; // 'tenant' par défaut
const isValidContext = APP_CONTEXT === 'tenant' || APP_CONTEXT === 'owner';
if (!isValidContext) {
  console.warn(`⚠️ VITE_APP_CONTEXT invalide: "${APP_CONTEXT}". Utilisation de "tenant" par défaut.`);
}

// Extraction du project_ref depuis l'URL Supabase pour construire la clé de stockage
// Format URL: https://<project-ref>.supabase.co
const projectRefMatch = SUPABASE_URL.match(/https?:\/\/([^.]+)\.supabase\.co/);
const projectRef = projectRefMatch ? projectRefMatch[1] : 'default';

// Clé de stockage isolée par contexte pour éviter les collisions de session
// Format: sb-<project-ref>-auth-token-<context>
const storageKey = `sb-${projectRef}-auth-token-${isValidContext ? APP_CONTEXT : 'tenant'}`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: storageKey, // Isolation des sessions par contexte (tenant vs owner)
    persistSession: true,
    autoRefreshToken: true,
  }
});